export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  USERNAME_TAKEN: 'AUTH_USERNAME_TAKEN',
  WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
  CAPTCHA_REQUIRED: 'AUTH_CAPTCHA_REQUIRED',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_REUSED: 'AUTH_TOKEN_REUSED',
  INTEGRATION_ALREADY_LINKED: 'INTEGRATION_ALREADY_LINKED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
